[build]
  # Build command for React Native Web (if converting to web)
  command = "npm run build"
  # Output directory
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}

# API redirects if you have a backend
[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/:splat"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://your-domain.com/*"
  to = "https://your-domain.com/:splat"
  status = 301
  force = true